project:
  type: website
  resources:
    - ads.txt
    - CNAME
execute:
  echo: false

website:
  title: "Ammar Aldawood"
  site-url: https://ammaraldawood.com/blog
  description: "Blog"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: projects/projects.qmd
        text: Projects
      - href: blog/welcome.qmd
        text: Blog
      - href: _site/blog/welcome.xml
        icon: rss
  google-analytics: "G-QC859BHLY4"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true

adsense:
  publisher-id: pub-4576710901770304

filters:
  - adsense
