project:
  type: website
  resources:
    - ads.txt

website:
  title: "Ammar Aldawood"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: blog/welcome.qmd
        text: Blog
      - href: projects/projects.qmd
        text: Projects
    tools:
      - icon: github
        href: https://github.com/ammaraldawood
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/ammar-aldawood/
        target: _blank
      - icon: twitter-x
        href: https://x.com/aldawood_ammar
        target: _blank
      - icon: youtube
        href: https://www.youtube.com/@Ammar_Aldawood
        target: _blank
      - icon: envelope-at-fill
        href: mailto:aldawoodammar@gmail.com
        target: _blank
  google-analytics: "G-QC859BHLY4"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

adsense:
  publisher-id: pub-4576710901770304

filters:
  - adsense
