project:
  type: website

website:
  title: "Ammar Aldawood"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: blog/welcome.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: services.qmd
        text: Services
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
